# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bazzite-ai-hypr-cuda
description: "Bazzite DX NVIDIA (latest) + Hyprland (Jakoolit) + CUDA + TensorRT + Fooocus + ComfyUI + pre-cached models"
image-version: latest
blue-build-tag: latest
base-image: ghcr.io/ublue-os/bazzite-dx-nvidia:latest

modules:
  # 🧰 Gaming & system tools
  - type: rpm-ostree
    install:
      - heroic-games-launcher
      - wine
      - wine-gecko
      - wine-mono
      - winetricks
      - vulkan-tools
      - goverlay
      - mangohud
      - protonup-qt
      - nvtop
      - lutris
      - gamemode
      - gamescope
      - steam
      - python3
      - python3-pip
      - python3-virtualenv
      - git
      - wget
      - aria2
      - curl
      - tar
      - xz
      - unzip

  # 🖥️ Hyprland + Jakoolit setup
  - type: script
    scripts:
      - name: hyprland-and-jakoolit
        content: |
          set -euo pipefail
          rpm-ostree install \
            hyprland waybar rofi mako wlogout swaylock-effects \
            hyprpaper hypridle hyprshot foot wl-clipboard grim slurp thunar file-roller \
            blueman gvfs gvfs-fuse xdg-desktop-portal-hyprland neovim kitty network-manager-applet

          git clone https://github.com/jakoolit/Hyprland-Dots.git /tmp/hyprdots
          mkdir -p /etc/skel/.config
          cp -r /tmp/hyprdots/.config/* /etc/skel/.config/ || true
          chown -R root:root /etc/skel/.config || true

          # NVIDIA Wayland tweaks (safe to set globally)
          echo 'export WLR_NO_HARDWARE_CURSORS=1' >> /etc/environment
          echo 'export __GLX_VENDOR_LIBRARY_NAME=nvidia' >> /etc/environment
          echo 'export GBM_BACKEND=nvidia-drm' >> /etc/environment
          echo 'export WLR_EGL_NO_MODIFIERS=1' >> /etc/environment
          echo 'export LIBVA_DRIVER_NAME=nvidia' >> /etc/environment

  # ⚙️ CUDA repo + Toolkit (auto-detect Fedora version)
  - type: script
    scripts:
      - name: cuda-repo-and-toolkit
        content: |
          set -euo pipefail
          FEDVER="$(. /etc/os-release && echo ${VERSION_ID})"
          echo "Detected Fedora VERSION_ID=$FEDVER"
          CUDA_REPO_URL="https://developer.download.nvidia.com/compute/cuda/repos/fedora${FEDVER}/x86_64/cuda-fedora${FEDVER}.repo"
          echo "Adding CUDA repo: $CUDA_REPO_URL"
          curl -fsSL "$CUDA_REPO_URL" -o /etc/yum.repos.d/cuda.repo || {
            echo "Failed to add CUDA repo for Fedora $FEDVER"
            exit 1
          }
          rpm-ostree install cuda-toolkit

          cat <<'EOS' > /etc/profile.d/cuda.sh
          export PATH=/usr/local/cuda/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
          export CUDA_CACHE_PATH=/var/cache/cuda
          EOS
          chmod +x /etc/profile.d/cuda.sh
          mkdir -p /var/cache/cuda && chmod 777 /var/cache/cuda

  # 🧠 TensorRT + cuDNN + PyTorch CUDA venv
  - type: script
    scripts:
      - name: tensorrt-cudnn-pytorch
        content: |
          set -euo pipefail
          FEDVER="$(. /etc/os-release && echo ${VERSION_ID})"
          ML_REPO_URL="https://developer.download.nvidia.com/compute/machine-learning/repos/fedora${FEDVER}/x86_64/nvidia-machine-learning.repo"
          echo "Adding NVIDIA ML repo: $ML_REPO_URL"
          curl -fsSL "$ML_REPO_URL" -o /etc/yum.repos.d/nvidia-ml.repo || {
            echo "Failed to add NVIDIA ML repo"
            exit 1
          }
          rpm-ostree install tensorrt-devel tensorrt-libs cudnn cudnn-devel cuda-nvml-devel cuda-nvrtc-devel

          python3 -m venv /opt/torch-venv
          source /opt/torch-venv/bin/activate
          pip install --upgrade pip wheel
          # Use CUDA 12.1 wheels (compatible with latest driver stack)
          pip install torch torchvision torchaudio xformers --extra-index-url https://download.pytorch.org/whl/cu121
          deactivate

          cat <<'EOS' > /etc/profile.d/pytorch_env.sh
          export PATH=/opt/torch-venv/bin:$PATH
          EOS
          chmod +x /etc/profile.d/pytorch_env.sh

  # 🤖 Fooocus install + ComfyUI install + pre-cache SDXL models
  - type: script
    scripts:
      - name: fooocus-comfyui-setup
        content: |
          set -euo pipefail

          # --- Fooocus ---
          mkdir -p /opt/fooocus
          if [ ! -d /opt/fooocus/.git ]; then
            git clone https://github.com/lllyasviel/Fooocus.git /opt/fooocus
          fi
          cd /opt/fooocus
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel
          pip install torch torchvision torchaudio xformers --extra-index-url https://download.pytorch.org/whl/cu121
          if [ -f requirements_versions.txt ]; then
            pip install -r requirements_versions.txt
          else
            pip install -r requirements.txt || true
          fi
          deactivate

          # --- ComfyUI ---
          mkdir -p /opt/comfyui
          if [ ! -d /opt/comfyui/.git ]; then
            git clone https://github.com/comfyanonymous/ComfyUI.git /opt/comfyui
          fi
          cd /opt/comfyui
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel
          pip install torch torchvision torchaudio xformers --extra-index-url https://download.pytorch.org/whl/cu121
          pip install -r requirements.txt
          deactivate

          # --- Pre-download models ---
          mkdir -p /opt/fooocus/models /opt/comfyui/models/checkpoints /opt/comfyui/models/controlnet
          aria2c -x 8 -d /opt/fooocus/models -o sdxl_base_1.0.safetensors \
            https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sdxl_base_1.0.safetensors || true
          aria2c -x 8 -d /opt/fooocus/models -o sdxl_refiner_1.0.safetensors \
            https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sdxl_refiner_1.0.safetensors || true
          aria2c -x 8 -d /opt/fooocus/models -o sdxl_vae.safetensors \
            https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors || true
          aria2c -x 8 -d /opt/comfyui/models/controlnet -o controlnet_canny.safetensors \
            https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_canny.safetensors || true

          # Desktop launchers
          cat <<'EOS' > /usr/share/applications/fooocus.desktop
          [Desktop Entry]
          Name=Fooocus
          Exec=bash -c "cd /opt/fooocus && ./venv/bin/python entry_with_update.py"
          Type=Application
          Icon=applications-graphics
          Categories=Graphics;AI;
          EOS

          cat <<'EOS' > /usr/share/applications/comfyui.desktop
          [Desktop Entry]
          Name=ComfyUI
          Exec=bash -c "cd /opt/comfyui && ./venv/bin/python main.py --cuda --listen 127.0.0.1 --port 8188"
          Type=Application
          Icon=applications-graphics
          Categories=Graphics;AI;
          EOS

          chmod -R 755 /opt/fooocus /opt/comfyui

  # 🔁 Auto-updates
  - type: script
    scripts:
      - name: enable-auto-updates
        content: |
          systemctl enable gamemoded.service || true
          systemctl enable rpm-ostreed-automatic.timer
          systemctl enable podman-auto-update.timer
